{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "flowmanager-agent.fullname" . }}-deploy
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "flowmanager-agent.name" . }}
    chart: {{ template "flowmanager-agent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "flowmanager-agent.fullname" . }}-deploy
  labels:
    app: {{ template "flowmanager-agent.name" . }}
    chart: {{ template "flowmanager-agent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "flowmanager-agent.fullname" . }}-deploy
subjects:
  - name: {{ template "flowmanager-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
    kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "flowmanager-agent.fullname" . }}-read
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "flowmanager-agent.name" . }}
    chart: {{ template "flowmanager-agent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: 
  - "" 
  resources:
  - secrets
  - configmaps
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "flowmanager-agent.fullname" . }}-read
  labels:
    app: {{ template "flowmanager-agent.name" . }}
    chart: {{ template "flowmanager-agent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "flowmanager-agent.fullname" . }}-read
subjects:
  - name: {{ template "flowmanager-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
    kind: ServiceAccount
{{- end -}}