apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowmanager-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "flowmanager-agent"
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: flowmanager-agent
        tier: backend
    spec:
      containers:
      - name: flowmanager-agent
        image: flowmanager-agent:stable
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: ACCEPT_EULA
          value: "false"
        - name: NAME                       # name of the agent
          value: GLOBAL
        - name: DOSA
          value: /conf/dosa.json
        - name: DOSA_KEY
          value: /conf/dosa-key.pem
        - name: DOSA_KEY_PASSWORD         # to be set if the KEY is secured
          value: ""
        - name: CACERT
          value:  ""                       # /conf/flowmanager-bridge.crt  Normally trusted by default
        - name: INSECURE
          value:  ""                       # Dangerous!!!
        - name: SERVER
          value:  "lptxrdnext01.lab1.lab.ptx.axway.int:8443"                       # should no be changed
        - name: COUNT
          value:  "2"                      # number of parallel connections
        - name: SENDLOGS
          value:  "true"                   # send agent logs to bridge for better support
        volumeMounts:
        # name must match the volume name below
        - name: dosa-secrets-volume
          mountPath: /conf
      volumes:
      - name: dosa-secrets-volume
        secret:
          secretName: dosa-secrets

