## Flow Manager Agent client deployment
version: "2.3"
services:
  flowmanager-agent:
    image: "docker.repository.axway.com/flowmanager-agent-docker-prod/2.0/release:<TAG>"
    restart: "always"
    environment:
      ACCEPT_EULA:             "false"
      NAME:                    ""
      DOSA:                    "/conf/fm-agent-dosa.json"
      DOSA_KEY:                "/conf/fm-agent-jwt-private-key.pem"
      DOSA_KEY_PASSWORD_FILE:  "/conf/password-file"
      HTTP_PORT:               "8080"
      AGENT_PORT:              "8443"
      WHITELIST:               "*"
      SERVER:                  ""
      SERVER_CA:               ""
      TLS_MIN_VERSION:         ""
      TLS_MAX_VERSION:         ""
    ports:
    # Agent HTTP port for relaying HTTP CFT calls, metrics, and health endpoints
    - "8080:8080"
    # Listening port for Bridge connections
    - "8443:8443"
    volumes:
      - ../conf:/conf:ro
